### ISSUE TITLE
Unable to load sonarqube

### ISSUE THREAD

**Issue by vinayraj-tcs** [marvinpuethe/docker-sonarqube-mysql#1]
Hi,

I have used the same dokcer-compse file from your project to setup sonarqube and MySQL. the docker container comes up fine, but i am unable to load the sonar qube page. it get "This site can’t be reached" error.

I tried commenting MySQL part from the yml and tried starting only sonarqube it worked fine. Looks like there is some issue with Mysql part. Can  you verify that.

**Comment by marvinpuethe** [comment]
Hi,

Unfortunately Sonarqube has discontinued support for MySQL:

"Support for MySQL has been dropped in Data Center Edition and deprecated for all other editions." (https://groups.google.com/forum/#!topic/sonarqube/Xv4QmRk4Rik)

If you don't have to rely on it, I would recommend to use the integration with Postgre SQL. I'm sure there will be support for a long time to come. On the following website you can find more information about using PostgreSQL with Sonarqube on Docker https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md

I was not able to resolve the issue you are facing but can verify the error with MySQL. I think this has to do with the JDBC Connection established to the database. The log for the MySQL container is fine but the sonarqube log shows the following error:

```
2019.03.04 21:39:55 INFO  web[][o.s.s.p.d.m.AutoDbMigration] Automatically perform DB migration on fresh install
2019.03.04 21:39:56 INFO  web[][DbMigrations] Executing DB migrations...
2019.03.04 21:39:56 INFO  web[][DbMigrations] #1 'Create initial schema'...
2019.03.04 21:39:56 ERROR web[][DbMigrations] #1 'Create initial schema': failure | time=76ms
2019.03.04 21:39:56 ERROR web[][DbMigrations] Executed DB migrations: failure | time=80ms
2019.03.04 21:39:56 ERROR web[][o.s.s.p.Platform] Web server startup failed
java.lang.IllegalStateException: Fail to execute CREATE TABLE active_dashboards (id INTEGER NOT NULL AUTO_INCREMENT,dashboard_id INTEGER NOT NULL,user_id INTEGER NULL,order_index INTEGER NULL, CONSTRAINT pk_active_dashboards PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin
        at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:97)
        at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:77)
        at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:117)
        at org.sonar.server.platform.db.migration.version.v56.CreateInitialSchema.createActiveDashboards(CreateInitialSchema.java:512)
        at org.sonar.server.platform.db.migration.version.v56.CreateInitialSchema.execute(CreateInitialSchema.java:51)
        at org.sonar.server.platform.db.migration.step.DdlChange.execute(DdlChange.java:45)
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:75)
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:67)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:52)
        at org.sonar.server.platform.db.migration.engine.MigrationEngineImpl.execute(MigrationEngineImpl.java:68)
        at org.sonar.server.platform.db.migration.AutoDbMigration.start(AutoDbMigration.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
        at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startSafeModeContainer(Platform.java:203)
        at org.sonar.server.platform.Platform.doStart(Platform.java:104)
        at org.sonar.server.platform.Platform.doStart(Platform.java:95)
        at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:46)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'active_dashboards' already exists
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
        at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:175)
        at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:175)
        at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:82)
        ... 40 common frames omitted
2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2019.03.04 21:39:58 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

If you are absolutely dependent on the use of MySQL, I can work together with you on a solution.

Greetings from Germany,
Marvin

**Comment by marvinpuethe** [comment]
As Sonarqube dropped support for MySQL I'm closing this issue. I've added this statement to the ReadMe (https://github.com/marvinpuethe/docker-sonarqube-mysql/commit/ae312aac99db54406429f676a71f0ce627440c72)

**Comment by wuyongdec** [comment]
you can update a postgres version

**Comment by marvinpuethe** [comment]
> you can update a postgres version

Can you clarify your comment? Would you like me to create a compose file for postgres?

**Comment by superATM** [comment]
> 
> 
> Hi,
> 
> Unfortunately Sonarqube has discontinued support for MySQL:
> 
> "Support for MySQL has been dropped in Data Center Edition and deprecated for all other editions." (https://groups.google.com/forum/#!topic/sonarqube/Xv4QmRk4Rik)
> 
> If you don't have to rely on it, I would recommend to use the integration with Postgre SQL. I'm sure there will be support for a long time to come. On the following website you can find more information about using PostgreSQL with Sonarqube on Docker https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md
> 
> I was not able to resolve the issue you are facing but can verify the error with MySQL. I think this has to do with the JDBC Connection established to the database. The log for the MySQL container is fine but the sonarqube log shows the following error:
> 
> ```
> 2019.03.04 21:39:55 INFO  web[][o.s.s.p.d.m.AutoDbMigration] Automatically perform DB migration on fresh install
> 2019.03.04 21:39:56 INFO  web[][DbMigrations] Executing DB migrations...
> 2019.03.04 21:39:56 INFO  web[][DbMigrations] #1 'Create initial schema'...
> 2019.03.04 21:39:56 ERROR web[][DbMigrations] #1 'Create initial schema': failure | time=76ms
> 2019.03.04 21:39:56 ERROR web[][DbMigrations] Executed DB migrations: failure | time=80ms
> 2019.03.04 21:39:56 ERROR web[][o.s.s.p.Platform] Web server startup failed
> java.lang.IllegalStateException: Fail to execute CREATE TABLE active_dashboards (id INTEGER NOT NULL AUTO_INCREMENT,dashboard_id INTEGER NOT NULL,user_id INTEGER NULL,order_index INTEGER NULL, CONSTRAINT pk_active_dashboards PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:97)
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:77)
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:117)
>         at org.sonar.server.platform.db.migration.version.v56.CreateInitialSchema.createActiveDashboards(CreateInitialSchema.java:512)
>         at org.sonar.server.platform.db.migration.version.v56.CreateInitialSchema.execute(CreateInitialSchema.java:51)
>         at org.sonar.server.platform.db.migration.step.DdlChange.execute(DdlChange.java:45)
>         at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:75)
>         at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:67)
>         at java.lang.Iterable.forEach(Iterable.java:75)
>         at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:52)
>         at org.sonar.server.platform.db.migration.engine.MigrationEngineImpl.execute(MigrationEngineImpl.java:68)
>         at org.sonar.server.platform.db.migration.AutoDbMigration.start(AutoDbMigration.java:62)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
>         at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
>         at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
>         at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
>         at org.picocontainer.behaviors.Stored.start(Stored.java:110)
>         at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
>         at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
>         at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
>         at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
>         at org.sonar.server.platform.Platform.start(Platform.java:211)
>         at org.sonar.server.platform.Platform.startSafeModeContainer(Platform.java:203)
>         at org.sonar.server.platform.Platform.doStart(Platform.java:104)
>         at org.sonar.server.platform.Platform.doStart(Platform.java:95)
>         at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:46)
>         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
>         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'active_dashboards' already exists
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
>         at com.mysql.jdbc.Util.getInstance(Util.java:408)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
>         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
>         at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
>         at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:175)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:175)
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:82)
>         ... 40 common frames omitted
> 2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
> 2019.03.04 21:39:58 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
> 2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
> 2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
> ```
> 
> If you are absolutely dependent on the use of MySQL, I can work together with you on a solution.
> 
> Greetings from Germany,
> Marvin

Thank you so much, and I found the url https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md , it's doesn't work, could you please update it?

**Comment by superATM** [comment]
> 
> 
> Hi,
> 
> Unfortunately Sonarqube has discontinued support for MySQL:
> 
> "Support for MySQL has been dropped in Data Center Edition and deprecated for all other editions." (https://groups.google.com/forum/#!topic/sonarqube/Xv4QmRk4Rik)
> 
> If you don't have to rely on it, I would recommend to use the integration with Postgre SQL. I'm sure there will be support for a long time to come. On the following website you can find more information about using PostgreSQL with Sonarqube on Docker https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md
> 
> I was not able to resolve the issue you are facing but can verify the error with MySQL. I think this has to do with the JDBC Connection established to the database. The log for the MySQL container is fine but the sonarqube log shows the following error:
> 
> ```
> 2019.03.04 21:39:55 INFO  web[][o.s.s.p.d.m.AutoDbMigration] Automatically perform DB migration on fresh install
> 2019.03.04 21:39:56 INFO  web[][DbMigrations] Executing DB migrations...
> 2019.03.04 21:39:56 INFO  web[][DbMigrations] #1 'Create initial schema'...
> 2019.03.04 21:39:56 ERROR web[][DbMigrations] #1 'Create initial schema': failure | time=76ms
> 2019.03.04 21:39:56 ERROR web[][DbMigrations] Executed DB migrations: failure | time=80ms
> 2019.03.04 21:39:56 ERROR web[][o.s.s.p.Platform] Web server startup failed
> java.lang.IllegalStateException: Fail to execute CREATE TABLE active_dashboards (id INTEGER NOT NULL AUTO_INCREMENT,dashboard_id INTEGER NOT NULL,user_id INTEGER NULL,order_index INTEGER NULL, CONSTRAINT pk_active_dashboards PRIMARY KEY (id)) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_bin
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:97)
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:77)
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:117)
>         at org.sonar.server.platform.db.migration.version.v56.CreateInitialSchema.createActiveDashboards(CreateInitialSchema.java:512)
>         at org.sonar.server.platform.db.migration.version.v56.CreateInitialSchema.execute(CreateInitialSchema.java:51)
>         at org.sonar.server.platform.db.migration.step.DdlChange.execute(DdlChange.java:45)
>         at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:75)
>         at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:67)
>         at java.lang.Iterable.forEach(Iterable.java:75)
>         at org.sonar.server.platform.db.migration.step.MigrationStepsExecutorImpl.execute(MigrationStepsExecutorImpl.java:52)
>         at org.sonar.server.platform.db.migration.engine.MigrationEngineImpl.execute(MigrationEngineImpl.java:68)
>         at org.sonar.server.platform.db.migration.AutoDbMigration.start(AutoDbMigration.java:62)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
>         at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
>         at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
>         at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
>         at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
>         at org.picocontainer.behaviors.Stored.start(Stored.java:110)
>         at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
>         at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
>         at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
>         at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
>         at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
>         at org.sonar.server.platform.Platform.start(Platform.java:211)
>         at org.sonar.server.platform.Platform.startSafeModeContainer(Platform.java:203)
>         at org.sonar.server.platform.Platform.doStart(Platform.java:104)
>         at org.sonar.server.platform.Platform.doStart(Platform.java:95)
>         at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:46)
>         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
>         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
>         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
>         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
>         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'active_dashboards' already exists
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
>         at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
>         at com.mysql.jdbc.Util.getInstance(Util.java:408)
>         at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976)
>         at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912)
>         at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
>         at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482)
>         at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440)
>         at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
>         at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:175)
>         at org.apache.commons.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:175)
>         at org.sonar.server.platform.db.migration.step.DdlChange$Context.execute(DdlChange.java:82)
>         ... 40 common frames omitted
> 2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
> 2019.03.04 21:39:58 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
> 2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
> 2019.03.04 21:39:58 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
> ```
> 
> If you are absolutely dependent on the use of MySQL, I can work together with you on a solution.
> 
> Greetings from Germany,
> Marvin

Thank you so much, and I found the url https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md , it's doesn't work, could you please update it?
